overblog_graphql:
    definitions:
        schema:
            query: RootQuery
        mappings:
            types:
                - type: attribute
                  dir: "%kernel.project_dir%/src/"
                  suffix: ~
                - type: yaml
                  dir: "%kernel.project_dir%/config/graphql/types"
                  suffix: null
